### ISSUE TITLE
NativeScript Angular - Upload Image to Azure Blob Storage

### ISSUE THREAD

**Issue by andresg747** [dzfweb/nativescript-azure-storage#4]
Hi. 
Is this compatible with a nativescript+angular app?

If it is, could you provide some hints on how can I use it in an existing component?

Thanks in advance. Great work!

**Comment by andresg747** [comment]
Nevermind. I have already integrated it to my app. 

Now I have another question. Can this be used to upload an image? (bitmap)

I'm trying to upload an image generated from the nativescript-drawingpad plugin and I'm getting:

`Error uploading: Error: Cannot convert object to Ljava/lang/String; at index 0`

I see the uploading function takes a string as a parameter. Can this be an image? Do I have to transform it first?

**Comment by dzfweb** [comment]
Hi,
you should convert the drawingpad result image to base64string and then send it to azure blob container. 

```
let base64string = ImageSourceModule.fromNativeSource(drawingPadResult).toBase64String('png');
```

**Comment by andresg747** [comment]
@dzfweb That's it! I was able to upload the image successfully. Now, my main intention is to get the direct url to that image, but the browser downloads the file and it's not readable. Do I have to decode before opening the file?

I want to draw a signature on device and get the image => Upload to azure => share direct link to get the PNG image.

Thank you very much for your help. If I make it work, I'll post the code to further help to others.

**Comment by abhishekkant** [comment]
> @dzfweb That's it! I was able to upload the image successfully. Now, my main intention is to get the direct url to that image, but the browser downloads the file and it's not readable. Do I have to decode before opening the file?
> 
> I want to draw a signature on device and get the image => Upload to azure => share direct link to get the PNG image.
> 
> Thank you very much for your help. If I make it work, I'll post the code to further help to others.

Did you ever get to completing your workflow: Image => Upload to Azure => Direct Iink to image? I am in similar situation and would be great to have some help on this..
